### ISSUE TITLE
Signal Terms of Service

### ISSUE THREAD

**Issue by Cerberus0** [nanu-c/textsecure-qml#38]
Hello @nanu-c,

Apologies if this is the wrong venue to ask this question. I recently read [Signal's Terms of Service](https://signal.org/legal/#terms-of-service) (updated May 25, 2018), which states:

>**Signal’s Rights.** We own all copyrights, trademarks, domains, logos, trade dress, trade secrets, patents, and other intellectual property rights associated with our Services. You may not use our copyrights, trademarks, domains, logos, trade dress, patents, and other intellectual property rights unless you have our written permission. To report copyright, trademark, or other intellectual property infringement, please contact abuse@signal.org.

The app you are distributing [on OpenStore](https://open-store.io/app/textsecure.nanuc) appears to be using, at the very least, Signal's name and logo. Have you received written permission from Signal Messenger LLC. to use their copyrights, trademarks, domains, logos, trade dress, patents, or other intellectual property rights?

**Comment by nanu-c** [comment]
Why are you asking?

**Comment by five-c-d** [comment]
I cannot speak as to why Cerberus0 was asking, but I can comment that the main reason to be careful with unofficial forks that re-use the same name as the upstream project, is that there is a risk that the trademark will become genericized (cf uppercase Kleenex<sup>TM</sup> and Google<sup>TM</sup> which eventually became kleenex and googling the generic lowercase terms).  

It is great that you are working on maintaining an unofficial fork of Signal-fka-TextSecure for a platform that the official devs have not managed to support, but you are not making clear in your helpdocs that the project at https://github.com/nanu-c/textsecure-qml is unofficial.  Your license is GPLv3 so you are good to go with copyright law, as far as I can see, but you need to make positive you are also good to go with trademark law.  Here is your readme:  

*  TextSecure UI in Go and QML 
*  TextSecure client for the Ubuntu Phone 
*  This is a Signal compatible client for the Ubuntu Phone, written in Go and QML. 
*  It builds upon the Go textsecure package... 

That should be altered to something more like this:  

*  <s>TextSecure</s> <ins>Unofficial signal-private-messenger</ins> UI in Go and QML 
*  <s>TextSecure</s> <ins>Unofficial signal</ins> client for the Ubuntu Phone 
*  This is <s>a Signal</s> <ins>an unofficial https://signal.org</ins> compatible client for the Ubuntu Phone, written in Go and QML. 
*  It builds upon the <ins>(also unofficial)</ins> Go textsecure package... 

When somebody downloads your textsecure.nanuc app, and installs it onto their UbuntuPhone, they will not mistakenly email support@signal.org when they find problems, because they will understand that textsecure.nanuc is unofficial.  Or at least, you will have been perfectly clear that it is unofficial  :-)   Whether the enduser understands or not, is something outside your control.  But what is inside your control, is to be clear with your own writings, and make sure you are keeping all your trademark-law i's dotted and t's crossed 

There is an unofficial support-forum for all endusers of signal, including unofficial ports like your for the UbuntuPhone (e.g. this support-request https://community.signalusers.org/t/ubuntu-touch-phone-computer-cannot-be-registered-using-desktop-app-but-it-works-with-the-chrome-web-app/4036 which is where I first heard about textsecure.nanuc).  People are welcome to ask for help there, with troubleshooting or compiling or whatever, although I'm not sure many endusers of UbuntuTouch are active in the signalUsers forum at the moment, so I usually direct folks here to this github issues-list.  

So, my recommendation is that you please change your helpdocs to make 100% crystal clear that 1) your project is not officially supported and so people should not seek tech support from Signal Foundation nor from OWS via support@signal.org, and 2) that they are free to ask for unofficial support here in your github or over at community.signalUsers.org or on reddit or whatever, plus 3) that your codebase is an unofficial lowercase signal client implementation, thus not the same thing as uppercase Signal<sup>TM</sup> codebase, to prevent any confusion
